### ISSUE TITLE
Error free code does not work

### ISSUE THREAD

**Issue by Eikosa** [davideicardi/DynamicExpresso#130] opened 2020-12-01 23:37 UTC
![image](https://user-images.githubusercontent.com/20538090/100809424-21d71c00-3447-11eb-93fa-188481a8a184.png)

**Comment by bortolin** [comment] 2020-12-02 23:27
This work for me:

"demene#asd".Split('#')[1]

**Comment by Eikosa** [comment] 2020-12-03 02:30
I was actually using a string as a separator

**Comment by davideicardi** [comment] 2020-12-03 13:13
So it was not a bug right? I'm closing the issue.

**Closed by davideicardi** 2020-12-03 13:13 UTC
